### ISSUE TITLE
Could not find artifact uncomplicate:neanderthal:jar:0.10.0-SNAPSHOT

### ISSUE THREAD

**Issue by findmyway** [uncomplicate/bayadera#2]
In project.clj, the dependencies is `uncomplicate/neanderthal "0.10.0-SNAPSHOT"`, however the snapshot version is not uploaded to the (https://clojars.org/repo/).

**Comment by blueberry** [comment]
Please use neanderthal 0.10.0

**Comment by blueberry** [comment]
I have also pushed a few minor changes and updated the neanderthal dependency.
